[package]
name = "sp-tracing"
version = "2.0.0-rc5"
license = "Apache-2.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "Instrumentation primitives and macros for Substrate."

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-std = { version = "2.0.0-rc5", path = "../std", default-features = false}
codec = { version = "1.3.1", package = "parity-scale-codec", default-features = false}
tracing = { version = "0.1.18", default-features = false }
tracing-core = { version = "0.1.13", optional = true }
log = { version = "0.4.8", optional = true }
once_cell = { version = "1.4.0", optional = true}

[features]
default = [ "std" ]
with-tracing = [
    "codec/derive",
    "codec/full",
    "once_cell",
]
std = [
    "with-tracing",
    "tracing/std",
    "tracing-core",
    "codec/std",
    "sp-std/std",
    "log",
]
